packages:
  - api
  - docs
  - demo/*
  - demo/custom/valaxy-theme-custom
  - packages/*
  - packages/@valaxyjs/*
  - scripts
catalog:
  '@iconify-json/ant-design': ^1.2.3
  '@iconify-json/carbon': ^1.2.4
  '@iconify-json/logos': ^1.2.3
  '@iconify-json/ri': ^1.2.3
  '@iconify-json/simple-icons': ^1.2.14
  '@iconify-json/vscode-icons': ^1.2.3
  typescript: '5.6'
  vite: ^6.0.3
