packages:
  - api
  - docs
  - demo/*
  - demo/custom/valaxy-theme-custom
  - packages/*
  - packages/@valaxyjs/*
  - scripts
catalog:
  '@iconify-json/ant-design': ^1.2.5
  '@iconify-json/carbon': ^1.2.8
  '@iconify-json/logos': ^1.2.4
  '@iconify-json/ri': ^1.2.5
  '@iconify-json/simple-icons': ^1.2.27
  '@iconify-json/vscode-icons': ^1.2.16
  typescript: ^5.8.2
  unbuild: ^3.5.0
  vite: ^6.2.1
  vue-i18n: ^11.1.2
  zx: ^8.4.0
  consola: ^3.4.0
onlyBuiltDependencies:
  - vue-demi
