packages:
  - api
  - docs
  - demo/*
  - demo/custom/valaxy-theme-custom
  - packages/*
  - packages/@valaxyjs/*
  - scripts
catalog:
  '@iconify-json/ant-design': ^1.2.5
  '@iconify-json/carbon': ^1.2.5
  '@iconify-json/logos': ^1.2.4
  '@iconify-json/ri': ^1.2.5
  '@iconify-json/simple-icons': ^1.2.17
  '@iconify-json/vscode-icons': ^1.2.6
  typescript: ^5.7.2
  unbuild: ^3.0.1
  vite: ^6.0.5
