packages:
  - api
  - docs
  - demo/*
  - demo/custom/valaxy-theme-custom
  - packages/*
  - packages/@valaxyjs/*
  - scripts
catalog:
  '@iconify-json/ant-design': ^1.2.5
  '@iconify-json/carbon': ^1.2.8
  '@iconify-json/logos': ^1.2.4
  '@iconify-json/ri': ^1.2.5
  '@iconify-json/simple-icons': ^1.2.33
  '@iconify-json/vscode-icons': ^1.2.20
  '@unhead/addons': ^2.0.8
  '@unhead/schema-org': ^2.0.8
  '@unhead/vue': ^2.0.8
  consola: ^3.4.2
  typescript: ^5.8.3
  unbuild: ^3.5.0
  unhead: ^2.0.8
  vite: ^6.3.3
  vue-i18n: ^11.1.3
  zx: ^8.5.3
onlyBuiltDependencies:
  - vue-demi
